### ISSUE TITLE
Issue with packagist

### ISSUE THREAD

**Issue by nicolasThal** [dekalee/php-autopilothq#4]
Hi,

I saw that you have released the tag 0.1.1 on your github repository but this information hasn't been transmitted to packagist.

Could you update the packagist informations? That would allow me to use the last version of your library :).

Thank you very much,

Nicolas

**Comment by ruskiyos** [comment]
Fixed. Not sure why packagist wasn't recognizing it. I had to delete the tag and re-create it.
But it works now :)

**Comment by nicolasThal** [comment]
Thank you very much :)
