### ISSUE TITLE
Issue: Composer Referencing 0.1.1

### ISSUE THREAD

**Issue by woodwardmatt** [dekalee/php-autopilothq#7]
Hey Guys,

When configuring composer as follows:

{
    "require": {
       "picr/php-autopilothq": "*"
    }
}

It's downloading tag 0.1.1 (from GitHub) which (as you've already corrected in tag 0.1.2) has an incorrect reference to the url "triggers" (as opposed to "trigger") in the api call at Line 401 on /vendor/picr/php-autopilothq/src/AutopilotManager.php

    public function addContactToJourney($name, $contactId)
    {
        $response = $this->apiPost('triggers/' . $name . '/contact/' . $contactId);

        return $response;
    }

Was just scratching my head why i kept getting a 404 then spotted the issue. Just wanted to let you guys know in case anyone else comes across the same problem (plus I wasn't sure how to correct the reference, so apologies if there's a way I could have done this).

PS: Thanks for sharing your work on this, only started using it today so will provide any feedback / help I can as I get to grips with it :)

**Comment by nicolasThal** [comment]
Hi,

As a matter of fact this library was created not by me, but as the current user, I took on maintening this code.

I have some issues with packagist and I cannot update the configuration, this way all my new tags are not published.

I will advise you to add a `repository` section in your `composer.json` file :

```json  
    "repositories": [

        {
            "type": "vcs",
            "url": "https://github.com/dekalee/php-autopilothq"
        }
    ],
```

I will try to check with the packagist team how I can update my package informations !

Btw, if you are using Symfony, I have an internal bundle that configure the library for a better usage in Symfony.

If you want to try it, I can open-source it.

Regards,

Nicolas

**Comment by woodwardmatt** [comment]
Thanks for your response Nicolas, really appreciate it :)

I've manually changed my code for the time being, but will update the configuration to use this repo at some point as you suggest :) 

I'm just using this through pure php at the moment :)

Regards, Matt
